name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🔧 Refactoring'
    labels:
      - 'refactor'
  - title: '⛓️ Dependencies'
    collapse-after: 1
    labels:
      - 'dependencies'
  - title: '📖 Documentation'
    collapse-after: 1
    labels:
      - 'documentation'
exclude-labels:
  - 'skip-changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
autolabeler:
  - label: 'enhancement'
    branch:
      - '/^feature.+/'
  - label: 'bug'
    branch:
      - '/^(bug)?fix.+/'
    title:
      - '/fix/i'
  - label: 'refactor'
    branch:
      - '/^refactor.+/'
  - label: 'dependencies'
    files:
      - 'yarn.lock'
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/^docs{0,1}.+/'
  - label: 'skip-changelog'
    branch:
      - '/^develop/'